identifier: lfa9e2j8ufo1oew2
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: vaservah
homeFolder: C:\Users\coolp\Desktop\vaservah\vaservah
distFolder: dist/vaservah
outDir: C:\Users\coolp\Desktop\vaservah\vaservah\dist\static
handle404: ''
allowErrorCollect: false
