identifier: lfa9e2j8ufo1oew2
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: vaservah
homeFolder: /home/swagoverlord/Desktop/vaservah/vaservah
distFolder: dist/vaservah
outDir: /home/swagoverlord/Desktop/vaservah/vaservah/dist/static
handle404: ''
allowErrorCollect: false
